#!/bin/sh
cmds=
num_lines=0

for arg
do
	cmds="$cmds $((arg))d;"
	: $((num_lines++))
done

if [ $num_lines -eq 0 ]
then
	echo "Usage: $(basename $0) [key_num...]" >&2
	exit 1
fi

echo $cmds && echo "Deleted $num_lines keys"

#cat ~/.ssh/authorized_keys
