#!/bin/sh

prog="$(basename "$0")"
keyfile=~/.ssh/authorized_keys

keys_del() {
	local cmds=
	
	for arg; do
		cmds="$cmds $((arg))d;"
	done

	if [ $# -eq 0 ]; then
		echo "Usage: $prog del [key_num...]" >&2
		exit 1
	fi

	sed -i~ "$cmds" "$keyfile" && \
		echo "Deleted $# keys"
}

keys_add() {
	lines=$(cat $@ | sed '/ /!d' | tee -a "$keyfile" | wc -l)
	echo Added $lines keys
}

keys_list() {
	sed = "$keyfile" | sed 'N;s/\n/. /'
}

keys_help() {
	cat <<-EOF
	Usage: $prog <command> [options]
	Commands:
	    list    List ssh authorized keys
	    add     Add ssh authorized keys (one per line)
	    del     Delete ssh authorized keys (by line numbers)
	EOF
}

cmd="$1"
if [ -z "$cmd" ]; then
	keys_help
	exit
fi

shift
case "$cmd" in
	list) keys_list $@;;
	add) keys_add $@;;
	del) keys_del $@;;
	help) keys_help;;
	*) keys_help >&2 && exit 1;;
esac
